# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/alexmatos/flycast/shell/apple/emulator-ios/AltKit/CMakeLists.txt))

/Users/alexmatos/flycast/build-ios/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/homebrew/bin/cmake -S/Users/alexmatos/flycast -B/Users/alexmatos/flycast/build-ios
